In [1]:
import torch
from torch import nn

In [2]:
x=torch.randn(100,3)
layer=nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[-0.4532,  0.4661, -0.3224],
        [ 0.3914,  0.2374,  0.2032],
        [-0.0491,  0.5278, -0.4428],
        [ 0.0803,  0.1786,  0.4087],
        [ 0.1191,  0.1104,  0.0926]], requires_grad=True)
Parameter containing:
tensor([ 0.5704,  0.0215,  0.5463,  0.3204, -0.3796], requires_grad=True)


In [3]:
x=torch.randn(2,5)
print(x)
layer=nn.ReLU()
print(layer(x)) # 음수를 0으로 바꾼다

tensor([[ 0.1261, -0.1002, -0.2385,  0.8944,  0.7649],
        [-0.8163,  0.8177,  0.1794,  0.8900, -1.9746]])
tensor([[0.1261, 0.0000, 0.0000, 0.8944, 0.7649],
        [0.0000, 0.8177, 0.1794, 0.8900, 0.0000]])


In [4]:
x=torch.randn(3,7)
print(x)
drop = nn.Dropout(p=0.3) # p 는 죽일 확률, 통과하는 node 를 drop 한다
print(drop(x))

tensor([[ 1.1030, -1.4809, -0.0805, -1.4326, -2.5971,  0.6210,  0.1482],
        [ 0.1984, -1.1153, -1.6442, -0.5004, -1.3771, -0.8876,  1.2738],
        [-2.9493,  0.2669, -1.1588,  0.7165, -0.1659,  0.9614,  1.3419]])
tensor([[ 0.0000, -2.1156, -0.1151, -2.0466, -3.7102,  0.8871,  0.2117],
        [ 0.2834, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  1.8197],
        [-4.2133,  0.3813, -1.6554,  1.0236, -0.2370,  0.0000,  1.9170]])


In [5]:
class sample_model(nn.Module) :
    def __init__(self):
        super().__init__()
        self.drop_layer = nn.Sequential(nn.Linear(5,7), # 각 픽셀을 채널로 본다
                                    nn.Dropout(p=0.3)
                                    )
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model = sample_model()
model.train()
x=torch.randn(3,5)
print(model(x))


model.eval()
print(model(x)) # test 때는 다 살리고 모든 원소에 0.7만큼이 곱해진다

tensor([[-0.0000, -0.6839, -0.3406,  0.6230,  0.7870,  1.4430,  0.2070],
        [ 0.0000, -0.3364,  1.2570, -0.0000,  0.0000, -0.0000,  1.9957],
        [-0.0000, -0.0000,  0.0000, -0.2204, -0.8066,  0.0000, -0.7203]],
       grad_fn=<MulBackward0>)
tensor([[-0.2798, -0.4787, -0.2385,  0.4361,  0.5509,  1.0101,  0.1449],
        [ 0.6142, -0.2355,  0.8799, -0.0493,  0.6499, -1.0393,  1.3970],
        [-1.3016, -0.1446,  0.4031, -0.1543, -0.5646,  0.5906, -0.5042]],
       grad_fn=<AddmmBackward0>)


In [6]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # 필터 사이즈가 3 by 3 stride, padding 은 0이 디폴트이다
layer(torch.randn(32,1,5,5)).shape # 흑백사진 5 by 5 짜리 32개인데 channel 만 바뀜
# nn.Linear(3,5) # 1d data 이기 때문에 채 또는 개채를 원함
# nn.Conv2d(3,5) # 2d data 이기 때문에 채행열 또는 개채행열 형태로 줘야한다 개 * 3 * 행 * 열

torch.Size([32, 2, 5, 5])

In [7]:
layer = nn.Conv2d(3,5,3,stride=2,padding=1) # 3개 채널로 들어가서 5개 채널로 나오고 커널 사이즈는 3*3
layer.weight.shape

torch.Size([5, 3, 3, 3])

In [8]:
conv1=nn.Conv2d(1,8,6,stride=2) # 흑백사진의 8개의 특징을 뽑는다
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2=nn.Conv2d(8,16,3, padding=1)
print(conv2(conv1(x)).shape)

Maxpool=nn.MaxPool2d(kernel_size=2, stride=(2,2))
print(Maxpool(conv2(conv1(x))).shape) # 채널 개수는 유지된다

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [9]:
maxpool=nn.MaxPool2d(2) # 이걸로만 줘도 kernel_size=2  stride = (2,2)
x=torch.randn(1,1,6,6)
print(x.shape)
print(maxpool(x).shape)
print(maxpool(torch.randn(32,3,6,6)).shape) # 채널은 변화가 없다

torch.Size([1, 1, 6, 6])
torch.Size([1, 1, 3, 3])
torch.Size([32, 3, 3, 3])


In [10]:
avgpool=nn.AvgPool2d(2) # 이걸로만 줘도 kernel_size=2  stride = (2,2)
x=torch.randn(1,1,6,6)
print(x.shape)
print(avgpool(x).shape)
print(avgpool(torch.randn(32,3,6,6)).shape) # 채널은 변화가 없다

torch.Size([1, 1, 6, 6])
torch.Size([1, 1, 3, 3])
torch.Size([32, 3, 3, 3])


In [11]:
class CNN(nn.Module):
    def __init__(self) :
        super().__init__()

        self.conv1= nn.Conv2d(1,8,6,stride=2)
        self.conv2= nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2= nn.MaxPool2d(2)
        self.fc=nn.Linear(16*6*6,10)

    def forward(self, x) :
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        x = torch.flatten(x, start_dim=1)
        x = self.fc(x)
        return x

x=torch.randn(32,1,28,28)
model=CNN()
model(x).shape

torch.Size([32, 10])

.parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [29]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [13]:
model.parameters()

<generator object Module.parameters at 0x78c4b2141a80>

In [34]:
list(model.parameters())[0] # layer 0 의 weight 출력
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[-0.3468,  0.3231],
        [-0.2883,  0.3686],
        [-0.0053,  0.0751]], requires_grad=True)

In [65]:
# for transfer learning
# 기존의 학습된 모델을 불러온 다음에 다섯개를 분류하도록 바꾸고 재학습 시키고 싶다
# 애초에 학습을 잘 했기 때문에 앞부분은 얼리고 뒷 부분만 재학습하고싶기 때문이다
model = MLP()
print((model.parameters()))
print([p for p in model.parameters() if p.requires_grad], end="\n\n")

for p in (model.parameters()) :
    p.requires_grad = False # 전부다 false 로 둔다 전체 freeze
model.fc_out=nn.Linear(4,10)

params= [p for p in model.parameters() if p.requires_grad]
print(params) # 10*4 파라미터만 나온다

from torch import optim
optimizer = optim.Adam(params, lr=0.1)

<generator object Module.parameters at 0x78c3e1e9f0d0>
[Parameter containing:
tensor([[ 0.0174,  0.0401],
        [ 0.5883, -0.0950],
        [-0.1034, -0.2883]], requires_grad=True), Parameter containing:
tensor([-0.2945, -0.6316, -0.5731], requires_grad=True), Parameter containing:
tensor([[-0.0488,  0.0790,  0.3918],
        [ 0.1530, -0.5444,  0.2007],
        [-0.4651, -0.3863,  0.4828],
        [-0.5596, -0.4091, -0.5624]], requires_grad=True), Parameter containing:
tensor([-0.3343,  0.0782, -0.5554,  0.3955], requires_grad=True), Parameter containing:
tensor([[ 0.3146,  0.4200, -0.4280,  0.3499]], requires_grad=True), Parameter containing:
tensor([-0.2953], requires_grad=True)]

[Parameter containing:
tensor([[ 0.3320,  0.4198, -0.4424,  0.4328],
        [-0.1804,  0.2842,  0.3226,  0.3841],
        [ 0.4644, -0.2826, -0.1200,  0.4851],
        [ 0.2865, -0.1661,  0.1615, -0.0204],
        [ 0.2603, -0.3224, -0.1540,  0.3812],
        [-0.1171, -0.1280,  0.1649, -0.0378],
      

In [60]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[-0.3224,  0.0928],
        [ 0.2689, -0.5234],
        [ 0.6958,  0.5945]])
fc1.0.bias
Parameter containing:
tensor([ 0.3231, -0.1216, -0.5034])
fc2.0.weight
Parameter containing:
tensor([[-0.2259,  0.5339,  0.0008],
        [-0.4662,  0.2670, -0.3930],
        [-0.0307,  0.1550, -0.2224],
        [-0.0075, -0.1435,  0.0292]])
fc2.0.bias
Parameter containing:
tensor([ 0.2364,  0.1188,  0.0966, -0.3861])
fc_out.weight
Parameter containing:
tensor([[ 0.0038, -0.0100, -0.3636,  0.1592],
        [ 0.2929, -0.2792, -0.2464, -0.3132],
        [-0.1616, -0.2914, -0.3631, -0.2821],
        [-0.1581, -0.0815,  0.4878,  0.4663],
        [-0.1999,  0.4292,  0.4073,  0.1147],
        [-0.1461,  0.3589,  0.2366,  0.3418],
        [ 0.1731, -0.1623,  0.4322,  0.2349],
        [ 0.3901,  0.4902,  0.2387,  0.3989],
        [-0.4732, -0.2399,  0.0695,  0.0662],
        [-0.3898,  0.4730,  0.1328, -0.4269]], requires_grad=True)
fc_out.bias
Parameter containing

In [61]:
model.modules()

<generator object Module.modules at 0x78c3e1e9f220>

In [62]:
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ),
 Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=2, out_features=3, bias=True),
 ReLU(),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=3, out_features=4, bias=True),
 ReLU(),
 Linear(in_features=4, out_features=10, bias=True)]

In [69]:
print([m for m in model.modules() if isinstance(m,nn.Linear)], end = "\n\n")
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)], end = "\n\n")
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)]) # gradient vanishing 확인

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]

[Parameter containing:
tensor([[ 0.0174,  0.0401],
        [ 0.5883, -0.0950],
        [-0.1034, -0.2883]]), Parameter containing:
tensor([[-0.0488,  0.0790,  0.3918],
        [ 0.1530, -0.5444,  0.2007],
        [-0.4651, -0.3863,  0.4828],
        [-0.5596, -0.4091, -0.5624]]), Parameter containing:
tensor([[ 0.3320,  0.4198, -0.4424,  0.4328],
        [-0.1804,  0.2842,  0.3226,  0.3841],
        [ 0.4644, -0.2826, -0.1200,  0.4851],
        [ 0.2865, -0.1661,  0.1615, -0.0204],
        [ 0.2603, -0.3224, -0.1540,  0.3812],
        [-0.1171, -0.1280,  0.1649, -0.0378],
        [-0.2639,  0.3684, -0.1313,  0.2565],
        [ 0.0740,  0.3468, -0.1118, -0.4473],
        [-0.2198,  0.1457, -0.1015,  0.0328],
        [-0.4949,  0.3897, -0.4500,  0.4090]], requires_grad=True)]

[None, None, None]


In [70]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[ 3.2608, -0.5390],
        [ 0.3578, -1.2526],
        [ 1.9410,  0.7032]]), Parameter containing:
tensor([[-0.4404,  0.9349,  0.3352],
        [-0.7678, -0.8273,  0.2874],
        [-0.5276, -0.0886,  0.4459],
        [ 2.2280, -0.1088, -0.8963]]), Parameter containing:
tensor([[-0.3366,  0.3932,  1.1226, -0.0656],
        [ 0.2324, -0.0079, -0.5172,  0.1989],
        [-0.2029, -0.7795, -0.6597, -1.1412],
        [-0.8626, -0.4629,  0.5586, -1.2564],
        [ 0.0052,  0.6478,  0.3916,  0.1234],
        [-0.1667,  0.6475,  0.5794, -0.2721],
        [-0.5599, -0.4259, -0.0449, -1.0640],
        [ 0.8251, -0.6292, -0.5061, -0.2629],
        [ 0.6280,  0.9792,  0.7995, -0.8225],
        [-0.6603, -0.4367,  0.3568,  0.5394]], requires_grad=True)]


In [72]:
model.children()

<generator object Module.children at 0x78c3e1e9f610>

In [75]:
list(model.children()) # init 에서 만든 attribute 단위로 준다

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=4, out_features=10, bias=True)]

In [77]:
x = torch.randn(2,2)
list(model.children())[0](x) # 0번째 layer를 통과시켜

tensor([[0.0000, 0.0000, 0.0000],
        [1.0477, 0.0000, 1.4670]])

In [86]:
# print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
sub_network(x)

Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)


tensor([[0.0000, 0.0782, 0.0000, 0.3955],
        [0.0000, 0.0000, 0.0000, 1.4150]])

## ModuleList vs Sequential

In [96]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list) # * 안써도 된다

print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!! nn.Sequential 과 달리 이건 forward 함수가 내장되어 있지 않다

for layer in layers2:
    x=layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0-4): 5 x Linear(in_features=3, out_features=3, bias=True)
)
tensor([[0.1717, 0.2065, 0.3726]], grad_fn=<AddmmBackward0>)
tensor([[0.1717, 0.2065, 0.3726]], grad_fn=<AddmmBackward0>)


In [99]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block) # Sequential 함수는 forward 함수에 하나만 넣도록 되어있다
print(model)
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
print(x,y)
print(model)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([-1.4715]) tensor([1.2752])
ModuleList(
  (0-1): 2 x small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([-0.0752], grad_fn=<ViewBackward0>) tensor([0.6366], grad_fn=<ViewBackward0>)
